# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import route_guide_pb2 as route__guide__pb2


class QueryNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskQuery = channel.unary_stream(
                '/QueryNode/AskQuery',
                request_serializer=route__guide__pb2.Query.SerializeToString,
                response_deserializer=route__guide__pb2.Result.FromString,
                )
        self.AddDocuments = channel.stream_unary(
                '/QueryNode/AddDocuments',
                request_serializer=route__guide__pb2.Document.SerializeToString,
                response_deserializer=route__guide__pb2.Status.FromString,
                )


class QueryNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AskQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDocuments(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.AskQuery,
                    request_deserializer=route__guide__pb2.Query.FromString,
                    response_serializer=route__guide__pb2.Result.SerializeToString,
            ),
            'AddDocuments': grpc.stream_unary_rpc_method_handler(
                    servicer.AddDocuments,
                    request_deserializer=route__guide__pb2.Document.FromString,
                    response_serializer=route__guide__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'QueryNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QueryNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AskQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/QueryNode/AskQuery',
            route__guide__pb2.Query.SerializeToString,
            route__guide__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddDocuments(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/QueryNode/AddDocuments',
            route__guide__pb2.Document.SerializeToString,
            route__guide__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DataNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskQuery = channel.unary_stream(
                '/DataNode/AskQuery',
                request_serializer=route__guide__pb2.Query.SerializeToString,
                response_deserializer=route__guide__pb2.Result.FromString,
                )
        self.WriteRequest = channel.stream_unary(
                '/DataNode/WriteRequest',
                request_serializer=route__guide__pb2.Document.SerializeToString,
                response_deserializer=route__guide__pb2.Status.FromString,
                )
        self.WriteReply = channel.unary_unary(
                '/DataNode/WriteReply',
                request_serializer=route__guide__pb2.Status.SerializeToString,
                response_deserializer=route__guide__pb2.Status.FromString,
                )


class DataNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AskQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteRequest(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.AskQuery,
                    request_deserializer=route__guide__pb2.Query.FromString,
                    response_serializer=route__guide__pb2.Result.SerializeToString,
            ),
            'WriteRequest': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteRequest,
                    request_deserializer=route__guide__pb2.Document.FromString,
                    response_serializer=route__guide__pb2.Status.SerializeToString,
            ),
            'WriteReply': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteReply,
                    request_deserializer=route__guide__pb2.Status.FromString,
                    response_serializer=route__guide__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AskQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/DataNode/AskQuery',
            route__guide__pb2.Query.SerializeToString,
            route__guide__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteRequest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/DataNode/WriteRequest',
            route__guide__pb2.Document.SerializeToString,
            route__guide__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataNode/WriteReply',
            route__guide__pb2.Status.SerializeToString,
            route__guide__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
